### ISSUE TITLE
ValueError: 'IBSpy/kmerGWAS/kmer_gwas.pyx' doesn't match any files

### ISSUE THREAD

**Issue by eylenth** [Uauy-Lab/IBSpy#11]
I want to install the python package
but I get the following error message:
```bash
    Complete output (11 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/eb-nlpiPW/pip-req-build-rsg1qlle/setup.py", line 43, in <module>
        compiler_directives={'language_level': "3"}),
      File "$INSTALLPATH/lib/python3.6/site-packages/Cython/Build/Dependencies.py", line 972, in cythonize
        aliases=aliases)
      File "$INSTALLPATH/lib/python3.6/site-packages/Cython/Build/Dependencies.py", line 815, in create_extension_list
        for file in nonempty(sorted(extended_iglob(filepattern)), "'%s' doesn't match any files" % filepattern):
      File "$INSTALLPATH/lib/python3.6/site-packages/Cython/Build/Dependencies.py", line 114, in nonempty
        raise ValueError(error_msg)
    ValueError: 'IBSpy/kmerGWAS/kmer_gwas.pyx' doesn't match any files
    ----------------------------------------

```
I have tried it with pip3 and with the following command. `python3 setup.py develop`
but none of them did work.

**Comment by homonecloco** [comment]
Also, can you try with python 3.7? we are not running unit test with older versions of python.

**Comment by eylenth** [comment]
I'm using redhat 7.6 as operating system.
I have also tried to install it with python3.7.0 and python 3.8.6 . But I'm getting the same error message every time..

**Comment by homonecloco** [comment]
@lucventurini , @ljyanesm  do you have any idea why this may happen?

**Comment by lucventurini** [comment]
The setup file does not find the pyx. Was the code pulled from GitHub? If so, is the file present?

If it was pulled from a python repository eg PyPI, then probably the pyx file is not in the MANIFEST.in file and therefore was not packaged in the wheel.

These would be my hypotheses

**Comment by eylenth** [comment]
indeed, it seems to be working with the github source.
it was not working from the source of pypi

**Comment by homonecloco** [comment]
Thanks  @lucventurini  and @eylenth , I need to double check how I uploaded the source file to pypi!
